### ISSUE TITLE
Same problem, did you find a solution?

### ISSUE THREAD

**Issue by NickThissen** [Flayed/PlaysTVCrash#1]
I seem to have the same issue, found your ticket on the PlaysTV website by random chance. Since they took it up to private communication I am clueless if there is anything we can do to resolve it from our end. Did you manage to prevent the crash or should we just wait for PlaysTV to fix it?

**Comment by Flayed** [comment]
Yes, I communicated directly with them, and they have the issue fixed in an upcoming release.  I was told that the release including this fix should be released either this week or early next week.

They sent me a build directly and I can confirm that it isn't crashing my app anymore.

Otherwise, they said application developers could contact them and get your application's name on the global blacklist (so PlaysTV won't target it now or in the future).
